# Generated by Django 3.0.6 on 2020-05-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='edition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
