# Generated by Django 3.0.6 on 2020-05-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
    ]
